### ISSUE TITLE
Hdr Issue

### ISSUE THREAD

**Issue by royhirshkowitz** [OpenImageDenoise/oidn#18] opened 2019-03-04 16:23 UTC
Tonemapped ldr images are working very nicely.  My first attempt at denoising hdr is failing.  
No errors reported but resulting data contains invalid floats (inf, ind, NaN, etc.)  Pfm file below appears to fail in my code and in the denoise sample app.  Units are cd/m^2.

win64 (Windows 10).  Using prebuilt OpenImageDenoise.dll.

[Example pfm](https://hirshkowitz0.blob.core.windows.net/misc/seating2.pfm)

**Comment by atafra** [comment] 2019-03-04 22:40
The issue was caused by infinities in the input, which were not filtered out correctly by the library. A fix has been committed to the `devel` branch and will be available in the next release. Meanwhile please rebuild the library from source or you could also avoid the issue by making sure that the input does not contain any infinities or NaNs. Thanks!

**Closed by atafra** 2019-03-04 22:40 UTC

**Comment by royhirshkowitz** [comment] 2019-03-05 00:41
Cleaned up the garbage on my end and it worked like a charm.  Thanks.
